function sendToAll  # FUNCION QUE  PERMITE ENVIAR  AL BOT DE TELEGRAM  TOKEN, DIRECTORIO DEL VIDEO Y VIDEO, ID CHAT DEL USUARIO DE TELEGRAM Y FECHA DE  ENVIO DEL VIDEO
{
  local path="$1" #RECIB  EL DIRECTORIO DEL  VIDEO
  fecha=`date +"%d/%m/%Y"` # LEE LA FECHA
	for q in $( ls $ALLOWED_BOT_USERS_FOLDER/* ); do
		local user=$(basename $q);
		local id=$(cat $q | tr -d '\040\011\012\015');  #LEE EL ID CHAT  DE LOS USUARIOS PERMITIDOS
    	 python3 ${PYTHON_VIDEO_SCRIPT} "$BOT_TOKEN" "$path" "$id" "$fecha" # EJECUTA EL BOT TELEEGRAM Y ENVIA TOKEN, DIRECTORIO DEL VIDEO Y VIDEO, ID CHAT DEL USUARIO DE TELEGRAM Y FECHA DE  ENVIO DEL VIDEO
	done
}



while [[ 1 ]]; do
  for nuevo in $( ls "${NEW_VIDEO_CREATED}" ); do  #CICLO QUE  PERMITE VER SI HAY ARCHIVO NUEVO Y LEER SU CONTENIDO(DIRRECION DEL VIDEO) 
      path=$(cat "${NEW_VIDEO_CREATED}/$nuevo" | tr -d '\040\011\012\015'); #LEE LA PRIMERA LINEA DEL ARCHIVO DE TEXTO
      sendToAll "$path" # ENVIA  LA DIRRECIION DEL VIDEO A LOS ADMINSTRADORES 
      mv "${NEW_VIDEO_CREATED}/$nuevo"  "${OLD_VIDEOS_FOLDER}" #MUEVE EL ARCHIVO A LA CARPETA OLD
  done
  sleep 1  #ESPERA 1 SEGUNDO
done

